<?php

namespace Phparch\SpaceTradersRest\Value\Ship\Event;

enum Type: string
{
    case REACTOR_OVERLOAD = "REACTOR_OVERLOAD";
    case ENERGY_SPIKE_FROM_MINERAL = "ENERGY_SPIKE_FROM_MINERAL";
    case SOLAR_FLARE_INTERFERENCE = "SOLAR_FLARE_INTERFERENCE";
    case COOLANT_LEAK = "COOLANT_LEAK";
    case POWER_DISTRIBUTION_FLUCTUATION = "POWER_DISTRIBUTION_FLUCTUATION";
    case MAGNETIC_FIELD_DISRUPTION = "MAGNETIC_FIELD_DISRUPTION";
    case HULL_MICROMETEORITE_STRIKES = "HULL_MICROMETEORITE_STRIKES";
    case STRUCTURAL_STRESS_FRACTURES = "STRUCTURAL_STRESS_FRACTURES";
    case CORROSIVE_MINERAL_CONTAMINATION = "CORROSIVE_MINERAL_CONTAMINATION";
    case THERMAL_EXPANSION_MISMATCH = "THERMAL_EXPANSION_MISMATCH";
    case VIBRATION_DAMAGE_FROM_DRILLING = "VIBRATION_DAMAGE_FROM_DRILLING";
    case ELECTROMAGNETIC_FIELD_INTERFERENCE = "ELECTROMAGNETIC_FIELD_INTERFERENCE";
    case IMPACT_WITH_EXTRACTED_DEBRIS = "IMPACT_WITH_EXTRACTED_DEBRIS";
    case FUEL_EFFICIENCY_DEGRADATION = "FUEL_EFFICIENCY_DEGRADATION";
    case COOLANT_SYSTEM_AGEING = "COOLANT_SYSTEM_AGEING";
    case DUST_MICROABRASIONS = "DUST_MICROABRASIONS";
    case THRUSTER_NOZZLE_WEAR = "THRUSTER_NOZZLE_WEAR";
    case EXHAUST_PORT_CLOGGING = "EXHAUST_PORT_CLOGGING";
    case BEARING_LUBRICATION_FADE = "BEARING_LUBRICATION_FADE";
    case SENSOR_CALIBRATION_DRIFT = "SENSOR_CALIBRATION_DRIFT";
    case HULL_MICROMETEORITE_DAMAGE = "HULL_MICROMETEORITE_DAMAGE";
    case SPACE_DEBRIS_COLLISION = "SPACE_DEBRIS_COLLISION";
    case THERMAL_STRESS = "THERMAL_STRESS";
    case VIBRATION_OVERLOAD = "VIBRATION_OVERLOAD";
    case PRESSURE_DIFFERENTIAL_STRESS = "PRESSURE_DIFFERENTIAL_STRESS";
    case ELECTROMAGNETIC_SURGE_EFFECTS = "ELECTROMAGNETIC_SURGE_EFFECTS";
    case ATMOSPHERIC_ENTRY_HEAT = "ATMOSPHERIC_ENTRY_HEAT";
}
