# Base image
FROM php:8.3-cli-alpine AS base

RUN apk update --no-cache && \
    apk upgrade --no-cache

FROM base AS build

RUN apk add --no-cache \
    $PHPIZE_DEPS \
    linux-headers

RUN apk add --no-cache \
    freetype-dev \
    jpeg-dev \
    icu-dev \
    libzip-dev

# PHP Extensions
## https://github.com/mlocati/docker-php-extension-installer
COPY --from=ghcr.io/mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

# Good to have if we ever need to do floating point math
RUN install-php-extensions gd xdebug intl zip

RUN docker-php-ext-enable opcache
RUN install-php-extensions apcu

# Not available with PHP source
RUN install-php-extensions redis

FROM base AS target

RUN contents="$(ls -1 /usr/local/lib/php/extensions)" && echo $contents

# Required libraries go here
RUN apk add --no-cache \
    # for GD extension
    freetype \
    jpeg \
    icu \
    libavif \
    libwebp \
    libxpm \
    # for redis extension
    lz4-libs \
    # for zip extension
    libzip \


# Get the extensions from build stage
# The no-debug-* dir will change with PHP versions
COPY --from=build /usr/local/lib/php/extensions/no-debug-non-zts-20230831/* /usr/local/lib/php/extensions/no-debug-non-zts-20230831
COPY --from=build /usr/local/etc/php/conf.d/* /usr/local/etc/php/conf.d

# Install composer
RUN curl -s http://getcomposer.org/installer | php && \
    mv composer.phar /usr/local/bin/composer

# Get our PHP.INI customization
COPY 99_php_custom.ini /usr/local/etc/php/conf.d

# 0.0.0.0 to accept external connections
CMD php -S 0.0.0.0:80 -t /var/www/web